"""Nested sway: the dual-output sidecar compositor.

`WL-1` is a window inside the session gamescope (the TV, main screen); `HEADLESS-1` is the
virtual output Sunshine captures and streams to the Deck.
"""

from __future__ import annotations

import shlex
from dataclasses import dataclass

from .profiles import Profile

MAIN_OUTPUT = "WL-1"
HEADLESS_OUTPUT = "HEADLESS-1"
MAIN_WORKSPACE = "main"
SECOND_WORKSPACE = "second"


@dataclass(frozen=True)
class OutputMode:
    width: int
    height: int
    refresh: int = 60

    def __str__(self) -> str:
        return f"{self.width}x{self.height}@{self.refresh}Hz"


@dataclass(frozen=True)
class CompositorSpec:
    profile: Profile
    env_dump: str
    tv: OutputMode = OutputMode(1920, 1080)
    second: OutputMode = OutputMode(1280, 800)


def render_config(spec: CompositorSpec) -> str:
    profile = spec.profile
    lines = [
        f"# generated by sdss for profile {profile.id} — do not edit",
        "default_border none",
        "default_floating_border none",
        "titlebar_padding 0",
        "focus_follows_mouse no",
        "xwayland enable",
        "",
        f"output {MAIN_OUTPUT} mode {spec.tv} position 0 0",
        f"output {HEADLESS_OUTPUT} mode {spec.second} position {spec.tv.width} 0",
        "",
        f"workspace {MAIN_WORKSPACE} output {MAIN_OUTPUT}",
        f"workspace {SECOND_WORKSPACE} output {HEADLESS_OUTPUT}",
        "",
        "# everything lands on the TV unless it matches the second-screen rules below",
        f"assign [app_id=\".*\"] workspace {MAIN_WORKSPACE}",
        "",
    ]

    for criteria in profile.second_window.rules():
        lines.append(
            f"for_window [{criteria}] move container to workspace {SECOND_WORKSPACE}, "
            "fullscreen enable"
        )

    lines += [
        "",
        'for_window [app_id=".*"] fullscreen enable',
        "",
        # The emulator is started by sdss on the host, not here: sway runs inside a
        # container and cannot exec host binaries.
        f"exec {shlex.quote(spec.env_dump)}",
    ]
    return "\n".join(lines) + "\n"


def environment(parent_wayland_display: str) -> dict[str, str]:
    """Env for the nested sway process itself."""
    return {
        # Wayland output = a window inside gamescope (TV); headless output = the stream.
        "WLR_BACKENDS": "wayland,headless",
        "WLR_WL_OUTPUTS": "1",
        "WLR_HEADLESS_OUTPUTS": "1",
        "WAYLAND_DISPLAY": parent_wayland_display,
        # gamescope only ever shows one window, so sway must not open extra surfaces.
        "WLR_NO_HARDWARE_CURSORS": "1",
    }
