"""Nested sway: the dual-output sidecar compositor.

The main output is a window inside the session gamescope (the TV screen) — `X11-1` when
connected to gamescope's per-game Xwayland, `WL-1` on the native-Wayland fallback (see
`runtime.parent_display`). `HEADLESS-1` is the virtual output Sunshine captures and
streams to the Deck.
"""

from __future__ import annotations

import shlex
from dataclasses import dataclass

from .profiles import Profile

MAIN_OUTPUT_X11 = "X11-1"
MAIN_OUTPUT_WAYLAND = "WL-1"
HEADLESS_OUTPUT = "HEADLESS-1"
MAIN_WORKSPACE = "main"
SECOND_WORKSPACE = "second"
DECK_PANEL_RESOLUTION = (1280, 800)

# HEADLESS-1 always targets the Deck's own panel resolution, never a per-profile
# native size. Emulators like Azahar render their second screen at a fixed native
# aspect ratio (e.g. exactly 320x240 for the 3DS bottom screen) and letterbox
# internally to fit whatever window/output size they're given — confirmed on
# hardware by resizing Azahar's Secondary Window to 1280x800 and finding the
# rendered content still exactly 960x720 (320x240 * 3), centered with black bars.
# Sizing HEADLESS-1 to each profile's tiny native size (e.g. 320x240) instead
# produced a squashed/stretched picture on the Deck, because Moonlight's client
# always requests its own fixed resolution and scales the incoming stream to
# fill it — there's no way to tell it "use the source's native size, no scaling".
# Matching the Deck's panel exactly sidesteps that scaling step entirely; the
# only remaining letterboxing is Azahar's own, which is proportionally correct.
DECK_PANEL_RESOLUTION = (1280, 800)


@dataclass(frozen=True)
class OutputMode:
    width: int
    height: int
    refresh: int = 60

    def __str__(self) -> str:
        return f"{self.width}x{self.height}@{self.refresh}Hz"


@dataclass(frozen=True)
class CompositorSpec:
    profile: Profile
    env_dump: str
    tv: OutputMode = OutputMode(1920, 1080)
    second: OutputMode = OutputMode(1280, 800)
    # Defaults to the Wayland output name so existing tests/dry-runs that don't care
    # about the parent backend keep reading the sway.conf they always have; the real
    # `sdss run` path always passes the name matching runtime.parent_display()'s choice.
    main_output: str = MAIN_OUTPUT_WAYLAND


def render_config(spec: CompositorSpec) -> str:
    profile = spec.profile
    # wlr_x11_backend refuses any "mode" sway asks for that isn't the size the parent
    # Xwayland root window already has ("Requested backend configuration failed,
    # searching for valid fallbacks"), leaving the output power:false and the compositor
    # never presenting a frame gamescope can show — so X11-1 must be left unsized and
    # simply takes gamescope's per-game Xwayland's own resolution. Only the native
    # Wayland fallback (WL-1) can and must request an exact mode (see runtime.py).
    is_x11_main = spec.main_output == MAIN_OUTPUT_X11
    main_output_line = f"output {spec.main_output} position 0 0"
    if not is_x11_main:
        main_output_line = f"output {spec.main_output} mode {spec.tv} position 0 0"
    # X11-1's real size isn't known until runtime, so spec.tv.width can't position
    # HEADLESS-1 correctly; push it far enough right that it never overlaps regardless.
    headless_x = 8192 if is_x11_main else spec.tv.width
    lines = [
        f"# generated by sdss for profile {profile.id} — do not edit",
        "default_border none",
        "default_floating_border none",
        "focus_follows_mouse no",
        # `enable` is lazy: sway only spawns Xwayland once an X11 client connects, so
        # $DISPLAY is still empty in the environment `exec` sees. `force` starts it during
        # compositor init, which is what makes the env dump below carry a usable DISPLAY.
        "xwayland force",
        "",
        main_output_line,
        f"output {HEADLESS_OUTPUT} mode {spec.second} position {headless_x} 0",
        "",
        f"workspace {MAIN_WORKSPACE} output {spec.main_output}",
        f"workspace {SECOND_WORKSPACE} output {HEADLESS_OUTPUT}",
        "",
        "# everything lands on the TV unless it matches the second-screen rules below",
        f"assign [app_id=\".*\"] workspace {MAIN_WORKSPACE}",
        "",
    ]

    for criteria in profile.second_window.rules():
        lines.append(
            f"for_window [{criteria}] move container to workspace {SECOND_WORKSPACE}, "
            "fullscreen enable"
        )

    lines += [
        "",
        'for_window [app_id=".*"] fullscreen enable',
        "",
        # The emulator is started by sdss on the host, not here: sway runs inside a
        # container and cannot exec host binaries.
        f"exec {shlex.quote(spec.env_dump)}",
        f"exec sdss-inputd --output {HEADLESS_OUTPUT}",
    ]
    return "\n".join(lines) + "\n"


def x11_fit_script(parent_display: str) -> str:
    """Shell snippet that resizes sway's own X11-1 window to the real TV resolution.

    `render_config` deliberately leaves X11-1 unsized because wlr_x11_backend has no
    working commit-time mode-set: sway's `output ... mode ...` — even with `--custom` —
    always fails with "Requested backend configuration failed, searching for valid
    fallbacks" no matter what size is requested, verified live against both a wrong and
    the exactly-correct size. It only reacts *passively* to a genuine external X11
    ConfigureWindow on its own toplevel window, the same as any WM-managed client. So
    this runs ourselves, deterministically, right after sway starts and before the
    emulator launches — instead of leaving the game's very first frame race gamescope's
    own after-the-fact resize of that window (which is slower and not guaranteed),
    which is what produced a real, correctly-rendered, but pillarboxed picture: azahar
    reads the small wlroots default (1024x768) as its "fullscreen" size before anything
    ever enlarges the window under it.

    Finding that window with `xdotool search --name` looked right in isolated testing
    but failed against every real Steam launch: wlroots sets only `_NET_WM_NAME` (EWMH)
    on it, never the classic ICCCM `WM_NAME` xdotool's `--name` actually matches against
    — so the search silently matched nothing (or, worse, the *root* window, whose
    geometry trivially satisfies a wildcard). `xwininfo -root -children` prints the
    title xdotool can't find and lists only genuine top-level children, so its own
    output is parsed directly instead.
    """
    title = f"wlroots - {MAIN_OUTPUT_X11}"
    display = shlex.quote(parent_display)
    grep_pattern = shlex.quote(f'"{title}"')
    return (
        "if command -v xdotool >/dev/null 2>&1 && command -v xwininfo >/dev/null 2>&1; then\n"
        f"  geometry=$(DISPLAY={display} xdotool getdisplaygeometry 2>/dev/null)\n"
        '  win="" i=0\n'
        '  while [ -z "$win" ] && [ "$i" -lt 20 ]; do\n'
        f"    win=$(DISPLAY={display} xwininfo -root -children 2>/dev/null "
        f"| grep -F {grep_pattern} | sed -n 's/^ *\\(0x[0-9a-f]*\\).*/\\1/p' | head -n1)\n"
        '    [ -n "$win" ] && break\n'
        "    sleep 0.1\n"
        "    i=$((i + 1))\n"
        "  done\n"
        '  if [ -n "$geometry" ] && [ -n "$win" ]; then\n'
        "    set -- $geometry\n"
        f'    DISPLAY={display} xdotool windowsize "$win" "$1" "$2" 2>/dev/null\n'
        "  fi\n"
        "fi\n"
    )


def environment(backend: str, parent_display: str) -> dict[str, str]:
    """Env for the nested sway process itself.

    `backend` is "x11" or "wayland" (see `runtime.parent_display`). Gamescope launches
    each Steam game against its own isolated per-game Xwayland instance
    (`STEAM_MULTIPLE_XWAYLANDS=1`) — steamcompmgr's window-ready/spinner-dismissal walk
    is scoped to windows on *that* display, not the shared desktop Wayland socket. A
    plain xdg_shell client connected to the shared gamescope-0 Wayland socket (the
    "wayland" backend below) is a real, correctly rendered window, but gamescope never
    associates it with the launched app and the loading spinner never clears. "x11" —
    wlroots' native X11 backend connecting straight to that per-game Xwayland `DISPLAY`
    — is what makes the window visible to that exact readiness check, so it must be
    preferred whenever Steam provides one.
    """
    env = {
        "WLR_NO_HARDWARE_CURSORS": "1",
    }

    if backend == "x11":
        return {
            **env,
            "WLR_BACKENDS": "x11,headless",
            "WLR_X11_OUTPUTS": "1",
            "WLR_HEADLESS_OUTPUTS": "1",
            "DISPLAY": parent_display,
        }
    return {
        **env,
        # Wayland output = a window inside gamescope (TV); headless output = the stream.
        "WLR_BACKENDS": "wayland,headless",
        "WLR_WL_OUTPUTS": "1",
        "WLR_HEADLESS_OUTPUTS": "1",
        "WAYLAND_DISPLAY": parent_display,
    }
