"""Auto-launch wrapper: makes `sdss run` fire from a normal Steam Library launch.

EmuDeck's launcher scripts (`azahar.sh`, `cemu.sh`) and the melonDS Flatpak export both
resolve a fixed path at launch time and `exec` whatever is there. SDSS never edits those
scripts or `shortcuts.vdf` — both are regenerated by EmuDeck/Steam ROM Manager and would
silently drop a direct edit. Instead, this module swaps the *file at that resolved path*
for a thin wrapper that calls `sdss run` on the real binary, which EmuDeck's scripts never
inspect by content.

Reused everywhere the toggle can flip (`sdss enable`/`disable`, and every `sdss status`
read, which is what the Decky plugin calls each time its panel opens) so this also
self-heals the common drift case: an EmuDeck version update re-downloads the AppImage
under the same filename, which would otherwise silently overwrite our wrapper.
"""

from __future__ import annotations

import os
import shlex
from pathlib import Path

from .profiles import Profile

_MARKER = "# sdss-wrapper:"


def _marker_line(profile_id: str) -> str:
    return f"{_MARKER} {profile_id} — managed by sdss, do not edit. See host/src/sdss/hooks.py."


def _resolve(profile: Profile) -> Path | None:
    if not profile.launcher_path:
        return None
    return Path(os.path.expanduser(profile.launcher_path))


def _shadow(path: Path) -> Path:
    return path.with_name(path.name + ".sdss-real")


def _previous_shadow(path: Path) -> Path:
    return path.with_name(f".{path.name}.sdss-previous")


def _head(path: Path) -> str:
    """First bytes of `path`, decoded loosely.

    Read in binary and bounded: when the wrapper is *not* installed these paths are real
    AppImages (Cemu is >100 MB), and this runs for every profile on every `sdss status`,
    which the Decky plugin calls each time its panel opens.
    """
    if path.is_symlink() or not path.is_file():
        return ""
    try:
        with path.open("rb") as handle:
            return handle.read(512).decode("utf-8", errors="ignore")
    except OSError:
        return ""


def _is_sdss_wrapper(path: Path) -> bool:
    """True if `path` is a wrapper we wrote, for *any* profile and any version.

    Deliberately matches only the marker prefix. `_is_wrapper` has to be exact to decide
    whether a wrapper is current, but destructive steps key off this looser check instead:
    misreading one of our own wrappers as a real binary would shadow the wrapper and point
    it at itself, which both discards the real binary and makes the launcher exec itself
    forever. Any file carrying the marker at all is never treated as a real binary.
    """
    return _MARKER in _head(path)


def _is_wrapper(path: Path, profile_id: str) -> bool:
    """A wrapper is always a plain file we wrote; a real AppImage/symlink never is."""
    return _marker_line(profile_id) in _head(path)


def _wrapper_script(profile: Profile, shadow: Path) -> str:
    sdss_bin = os.path.expanduser("~/.local/bin/sdss")
    command = profile.launcher_command or (str(shadow),)
    command_text = " ".join(shlex.quote(arg) for arg in command)
    return (
        f"#!/bin/bash\n"
        f"{_marker_line(profile.id)}\n"
        'export SDSS_EMULATOR_LD_PRELOAD="${LD_PRELOAD-}"\n'
        "unset LD_PRELOAD\n"
        f'exec {shlex.quote(sdss_bin)} run --profile {profile.id} -- {command_text} "$@"\n'
    )


def _write_wrapper(path: Path, profile: Profile, shadow: Path) -> None:
    """Put our wrapper at `path` without ever leaving `path` missing.

    The write goes to a temp file next to `path` and is then `os.replace`d into place, so a
    failure (ENOSPC, or the SIGKILL SteamOS sends the whole session on logout) can never
    leave the launcher path empty — which would be unrecoverable, since both `install` and
    `remove` need a file there to identify what to do.
    """
    tmp = path.with_name(f".{path.name}.sdss-tmp")
    try:
        tmp.write_text(_wrapper_script(profile, shadow))
        tmp.chmod(0o755)
        os.replace(tmp, path)
    except OSError:
        tmp.unlink(missing_ok=True)
        raise


def is_installed(profile: Profile) -> bool:
    path = _resolve(profile)
    return path is not None and path.exists() and _is_wrapper(path, profile.id)


def install(profile: Profile) -> bool:
    """Ensure `profile`'s launcher path is our wrapper. Returns True if it changed anything.

    Safe to call repeatedly: if a current wrapper is already in place it is left untouched.
    If a *new* real binary has appeared at the resolved path (for example after an EmuDeck
    update), the new binary is shadowed and re-wrapped. A wrapper with a missing shadow is
    deliberately left untouched because there is no safe original binary to restore.
    """
    path = _resolve(profile)
    if path is None:
        return False
    shadow = _shadow(path)
    previous = _previous_shadow(path)

    if not path.exists():
        # A previous run was killed between shadowing and writing the wrapper, so the
        # launcher path is missing while the real binary sits in the shadow. Nothing else
        # creates that state, and leaving it means the Steam entry never launches again.
        if shadow.exists() or shadow.is_symlink():
            _write_wrapper(path, profile, shadow)
            previous.unlink(missing_ok=True)
            return True
        return False

    if _is_wrapper(path, profile.id):
        previous.unlink(missing_ok=True)
        return False

    if _is_sdss_wrapper(path):
        # Ours, but stale (an older marker line, or another profile's). Rewrite it in place
        # rather than shadowing it: shadowing would discard the real binary and leave the
        # wrapper exec'ing itself.
        if not (shadow.exists() or shadow.is_symlink()):
            return False
        _write_wrapper(path, profile, shadow)
        previous.unlink(missing_ok=True)
        return True

    if shadow.exists() or shadow.is_symlink():
        previous.unlink(missing_ok=True)
        os.replace(shadow, previous)
        try:
            os.replace(path, shadow)
            try:
                _write_wrapper(path, profile, shadow)
            except OSError:
                os.replace(shadow, path)
                os.replace(previous, shadow)
                raise
        except OSError:
            if previous.exists() and not shadow.exists():
                os.replace(previous, shadow)
            raise
        previous.unlink(missing_ok=True)
        return True

    os.replace(path, shadow)
    try:
        _write_wrapper(path, profile, shadow)
    except OSError:
        os.replace(shadow, path)
        raise
    return True


def remove(profile: Profile) -> bool:
    """Restore the real binary/symlink in place of our wrapper. Returns True if it changed."""
    path = _resolve(profile)
    if path is None:
        return False
    shadow = _shadow(path)
    previous = _previous_shadow(path)
    if not (shadow.exists() or shadow.is_symlink()):
        previous.unlink(missing_ok=True)
        # Wrapper present but its shadow vanished — nothing safe to restore.
        return False
    if not (path.exists() or path.is_symlink()):
        # Killed between shadowing and writing the wrapper; the shadow is the real binary.
        pass
    elif not _is_sdss_wrapper(path):
        # A real binary is already back at the launcher path (an EmuDeck update landed
        # while SDSS was disabled). Leave it and keep the shadow rather than clobbering it.
        return False
    # rename() atomically replaces `path`; no separate unlink, so there is no window
    # where the launcher path is missing if this gets killed mid-operation.
    shadow.rename(path)
    previous.unlink(missing_ok=True)
    return True


def reconcile(profile: Profile, enabled: bool) -> bool:
    """Install or remove the wrapper to match `enabled`. Returns True if it changed anything."""
    return install(profile) if enabled else remove(profile)
