#!/usr/bin/env bash
# Install the Steam Machine host. All non-udev artifacts live below $HOME.
set -euo pipefail

ROOT="${1:?usage: install-host.sh <sdss-release-directory>}"
SUNSHINE_ID="dev.lizardbyte.app.Sunshine"
BIN_DIR="$HOME/.local/bin"

if [[ ! -f "$ROOT/host/pyproject.toml" || -L "$ROOT/host/pyproject.toml" ||
      ! -f "$ROOT/runtime/Containerfile" || -L "$ROOT/runtime/Containerfile" ||
      ! -f "$ROOT/packaging/install-udev-rule.sh" || -L "$ROOT/packaging/install-udev-rule.sh" ]]; then
    echo "invalid SDSS release directory: $ROOT" >&2
    exit 1
fi

if ! command -v flatpak >/dev/null || ! command -v podman >/dev/null; then
    echo "SteamOS needs both flatpak and podman for SDSS." >&2
    exit 1
fi

# shellcheck source=common.sh
source "$ROOT/packaging/common.sh"
install_flatpak "$SUNSHINE_ID" "Sunshine"

# SteamOS ships no pip and the rootfs is read-only, so `sdss` is a shim pointing at the
# installed release. The host package is standard-library only, so PYTHONPATH suffices.
# ROOT is interpolated through printf %q so a path containing spaces or quotes produces a
# valid shim rather than one that silently execs with a truncated PYTHONPATH.
mkdir -p "$BIN_DIR"
quoted_root="$(printf '%q' "$ROOT/host/src")"
cat > "$BIN_DIR/sdss" <<EOF
#!/usr/bin/env bash
# Generated by the SDSS installer. Re-run the installer to update.
export PYTHONPATH=$quoted_root\${PYTHONPATH:+:\$PYTHONPATH}
exec python3 -m sdss.cli "\$@"
EOF
chmod 0755 "$BIN_DIR/sdss"
echo "installed $BIN_DIR/sdss"

note_path "$BIN_DIR"

echo
echo "SDSS needs permission to exclusively read Sunshine's touch devices."
echo "Your sudo password is requested only to install its udev rule under /etc."
sudo "$ROOT/packaging/install-udev-rule.sh"

"$ROOT/runtime/build.sh"
"$ROOT/plugin/install.sh" "$ROOT"

"$BIN_DIR/sdss" doctor || true

cat <<'EOF'

Steam Machine setup is complete.

Turn Second Screen on from the SDSS Decky plugin (or `sdss enable`), then launch an
emulator with `sdss run -- <emulator>`. Re-run `sdss doctor` from Game Mode or an SSH
shell after sourcing /run/user/1000/gamescope-environment.
EOF
